Cleaning code and fix

diff --git a/debian/wiithon.postinst b/debian/wiithon.postinst
--- a/debian/wiithon.postinst
+++ b/debian/wiithon.postinst
@@ -1,30 +1,60 @@
-#!/bin/sh -e
+#!/bin/sh
+# postinst script for pfc
+#
+# see: dh_installdeb(1)
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+set -e
 
 #. /usr/share/debconf/confmodule
 #db_version 2.0
 
-chmod 755 /usr/share/wiithon/wiithon.py
-chmod 755 /usr/games/wiithon_wrapper
-chmod 755 /usr/games/wiithon_unrar
-chmod 755 /usr/share/wiithon/wiithon_autodetectar*.sh
-
-chmod 644 /usr/share/wiithon/recursos/glade/*.ui
-chmod 644 /usr/share/wiithon/recursos/imagenes/*.png
-chmod 644 /usr/share/applications/wiithon_usuario.desktop
- 
-chmod 777 /usr/share/wiithon/recursos/imagenes/caratulas
-chmod 777 /usr/share/wiithon/recursos/imagenes/discos
-
-ln -sf /usr/share/wiithon/wiithon.py /usr/games/wiithon
-ln -sf /usr/games/wiithon_wrapper /usr/share/wiithon/wiithon_wrapper
-ln -sf /usr/games/wiithon_unrar /usr/share/wiithon/wiithon_unrar
-
-echo
-echo "If you want run wiithon as normal user you must add it to 'disk' group."
-echo "Type: \"sudo gpasswd -a \$USER disk\" and restart your GNOME/KDE session."
-echo
-
 #db_input high wiithon/group-disk || true
 #db_go || true
 
-exit 0
+case "$1" in
+    configure)
+    
+        chmod 755 /usr/share/wiithon/wiithon.py
+        chmod 755 /usr/games/wiithon_wrapper
+        chmod 755 /usr/games/wiithon_unrar
+        chmod 755 /usr/share/wiithon/wiithon_autodetectar*.sh
+
+        chmod 644 /usr/share/wiithon/recursos/glade/*.ui
+        chmod 644 /usr/share/wiithon/recursos/imagenes/*.png
+        chmod 644 /usr/share/applications/wiithon_usuario.desktop
+         
+        chmod 777 /usr/share/wiithon/recursos/imagenes/caratulas
+        chmod 777 /usr/share/wiithon/recursos/imagenes/discos
+
+        ln -sf /usr/share/wiithon/wiithon.py /usr/games/wiithon
+        ln -sf /usr/games/wiithon_wrapper /usr/share/wiithon/wiithon_wrapper
+        ln -sf /usr/games/wiithon_unrar /usr/share/wiithon/wiithon_unrar
+
+        echo
+        echo "If you want run wiithon as normal user you must add it to 'disk' group."
+        echo "Type: \"sudo gpasswd -a \$USER disk\" and restart your GNOME/KDE session."
+        exit 0
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+        echo "no action for \`$1'" >&2
+        exit 0
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
