- postrm with real purge -> PURGE if you want delete covers & disc-arts - Nuevos proveedores - Versiones de BDD - More mini-fix

diff --git a/debian/wiithon.postrm b/debian/wiithon.postrm
--- a/debian/wiithon.postrm
+++ b/debian/wiithon.postrm
@@ -1,7 +1,61 @@
 #!/bin/sh -e
 
-test -L /usr/games/wiithon && rm /usr/games/wiithon
-test -L /usr/share/wiithon/wiithon_wrapper && rm /usr/share/wiithon/wiithon_wrapper
-test -L /usr/share/wiithon/wiithon_unrar && rm /usr/share/wiithon/wiithon_unrar
+# postrm script for libsocket6-perl
+#
+# see: dh_installdeb(1)
 
-exit 0
+set -e
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
+# for details, see /usr/share/doc/packaging-manual/
+
+case "$1" in
+    purge)
+        # repeat remove
+        test -d /usr/share/doc/wiithon && rm -f /usr/share/doc/wiithon/*
+        test -d /usr/share/doc/wiithon && rmdir /usr/share/doc/wiithon
+    
+        test -L /usr/games/wiithon && rm /usr/games/wiithon
+        test -L /usr/share/wiithon/wiithon_wrapper && rm /usr/share/wiithon/wiithon_wrapper
+        test -L /usr/share/wiithon/wiithon_unrar && rm /usr/share/wiithon/wiithon_unrar
+        
+        # purge
+        test -d /usr/share/wiithon/recursos/imagenes/caratulas/ && rm -f /usr/share/wiithon/recursos/imagenes/caratulas/*.png
+        test -d /usr/share/wiithon/recursos/imagenes/discos/ && rm -f /usr/share/wiithon/recursos/imagenes/discos/*.png
+        test -d /usr/share/wiithon/recursos/imagenes/caratulas && rmdir /usr/share/wiithon/recursos/imagenes/caratulas
+        test -d /usr/share/wiithon/recursos/imagenes/discos && rmdir /usr/share/wiithon/recursos/imagenes/discos
+        test -d /usr/share/wiithon/recursos/imagenes && rmdir /usr/share/wiithon/recursos/imagenes
+        test -d /usr/share/wiithon/recursos && rmdir /usr/share/wiithon/recursos
+        test -d /usr/share/wiithon && rmdir /usr/share/wiithon
+        exit 0
+        ;;
+    remove)
+        test -d /usr/share/doc/wiithon && rm -f /usr/share/doc/wiithon/*
+        test -d /usr/share/doc/wiithon && rmdir /usr/share/doc/wiithon
+    
+        test -L /usr/games/wiithon && rm /usr/games/wiithon
+        test -L /usr/share/wiithon/wiithon_wrapper && rm /usr/share/wiithon/wiithon_wrapper
+        test -L /usr/share/wiithon/wiithon_unrar && rm /usr/share/wiithon/wiithon_unrar
+        exit 0
+        ;;
+    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+        echo "no action for \`$1'"
+        exit 0
+        ;;
+    *)
+        echo "postrm called with unknown argument \`$1'"
+        exit 0
+        ;;
+esac
+
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
